### ISSUE TITLE
In Responsive table: Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by aamping** [local-insights/material-ui-next-responsive-table#13]
Hi, 

While in the mobile-size table. It appears the warning:
`Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>....`

My code:

`
          <Card style={{ margin: 20 }} key={key}>
            <CardHeader
              title={`Cistella: ${cistella.comandes[0].dia_entrega}`}
              subheader={`Preu Total: ${cistella.comandes.preu_unitat} `}
            />
            <CardContent>
              <ResponsiveTable columns={columns} data={cistella.comandes} />
            </CardContent>
          </Card>
`
any clue?

Thanks

**Comment by hrdymchl** [comment]
Hi @aamping, try upgrading to version `0.4.8`. We cleared this warning in that release.
